import '../modelo/Jogador.dart';

class JogadorController {
  List<Jogador> listarJogadores() {
    //criando lista
    return [
      //criado objeto
      Jogador(
        nome: 'Alisson',
        posicao: 'Gol',
        numero: 1,
        descricao: 'Titular, goleiro',
        imagemUrl: 'assets/imgs/Alisson.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Neymar',
        posicao: 'Atacante',
        numero: 10,
        descricao: 'Menino Ney que vai trazer o hexa se não cair',
        imagemUrl: 'assets/imgs/Neymar.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Vini Jr',
        posicao: 'Ponta Esquerda',
        numero: 7,
        descricao: 'Atua pelas pontas do campo',
        imagemUrl: 'assets/imgs/Vinicius Junior.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Bento',
        posicao: 'Goleiro',
        numero: 2,
        descricao: 'Reserva, Goleiro',
        imagemUrl: 'assets/imgs/Bento.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
Jogador(
        nome: 'Matheus',
        posicao: 'Atacante/Meia-Atacante',
        numero: 9,
        descricao: 'Jogador Versatil',
        imagemUrl: 'assets/imgs/Matheus.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Gabriel Martinelli',
        posicao: 'Atacante/Ponta-Direita',
        numero: 11,
        descricao: 'Atua pelas pontas do campo',
        imagemUrl: 'assets/imgs/gabriel martinelli.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Gabriel',
        posicao: 'Zagueiro',
        numero: 3,
        descricao: 'Xerife da Zaga',
        imagemUrl: 'assets/imgs/gabriel.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Marquinhos',
        posicao: 'Zagueiro',
        numero: 4,
        descricao: 'Lider do Time',
        imagemUrl: 'assets/imgs/marquinhos.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Wesley',
        posicao: 'Lateral Direito',
        numero: 5,
        descricao: 'Jogador Veloz',
        imagemUrl: 'assets/imgs/wesley.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Raphinha',
        posicao: 'Ponte-Esquerda',
        numero: 12,
        descricao: 'Cobrador de Faltas do Time',
        imagemUrl: 'assets/imgs/raphinha.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Luiz Henrique',
        posicao: 'Zagueiro',
        numero: 13,
        descricao: 'Jogador do drible e velocidade',
        imagemUrl: 'assets/imgs/Luiz Henrique.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Estevão ',
        posicao: 'Ponta-esquerda',
        numero: 14,
        descricao: 'Uma das Jovens Promesas do Brasil',
        imagemUrl: 'assets/imgs/estevao.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Eder',
        posicao: 'Zagueiro',
        numero: 7,
        descricao: 'Zagueiro Reserva/ consegue fazer a  lateral tambem',
        imagemUrl: 'assets/imgs/eder.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Danilo',
        posicao: 'Lateral-Direito',
        numero: 15,
        descricao: 'Lateral que atua como zagueiro tambem',
        imagemUrl: 'assets/imgs/danilo.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Casemiro',
        posicao: 'Volante',
        numero: 8,
        descricao: 'Volante titular e um dos lideres da equipe',
        imagemUrl: 'assets/imgs/casemiro.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Bruno',
        posicao: 'Volante',
        numero: 17,
        descricao: 'Jogador com otíma qualidade tecnica',
        imagemUrl: 'assets/imgs/bruno.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),
      Jogador(
        nome: 'Lucas',
        posicao: 'meio-Campista',
        numero: 16,
        descricao: 'Jogador com otíma qualidade tecnica',
        imagemUrl: 'assets/imgs/lucas.png',
        time: 'Brasil',
        nacionalidade: 'brasileiro',
      ),



    ];
  }
}

